spring.application.name=Opencord

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/opencord
spring.datasource.username=miranda
spring.datasource.password=miranda
spring.datasource.driver-class-name=org.postgresql.Driver

# MongoDB
spring.mongodb.uri=mongodb://miranda:miranda@localhost:27017/opencord?authSource=admin
spring.mongodb.representation.uuid=standard

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Logging (opcional, útil durante o desenvolvimento)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.flywaydb=INFO

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

api.security.token.secret="super-secret"

server.port=25565
